site_name: Alex Fries
nav:
    - Home: index.md
    - Resume: resume.md
    - About Me: about.md

remote_branch: 'master'

theme:
    name: material
    language: 'en'
    

extra:
  social: 
    - type: 'twitter'
      link: 'https://twitter.com/Carto_ALex'
    - type: 'github'
      link: 'https://github.com/acfries'

site_author: Alex Fries
