site_name: Alex Fries Carto

plugins:
  - awesome-pages:
      collapse_single_pages: true

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - My Resume: resume.md
  - About Me: about.md

remote_branch: 'master'

theme:
    name: 'material'
    custom_dir: 'theme'
    language: 'en'
    palette:
      primary: 'blue grey'
      accent: 'blue grey'
    logo:
      icon: 'terrain'
    feature:
      tabs: true
    include_sidebar: false

extra_css:
  - 'stylesheets/extra.css'

extra:
  social: 
    - type: 'twitter'
      link: 'https://twitter.com/Carto_ALex'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/alexander-fries-097685174/'
    - type: 'github'
      link: 'https://github.com/acfries'

site_author: Alex Fries
