site_name: Maps by Alex Fries

plugins:
  - awesome-pages:
      collapse_single_pages: false

markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Resume: resume/index.md
  - About: about/index.md

remote_branch: master

theme:
  name: material
  custom_dir: theme
  language: en
  palette:
    primary: brown
    accent: brown
  icon:
    logo: material/terrain
  features:
    - tabs
  font: Open Sans
  favicon: img/logo.ico

extra_css:
  - stylesheets/extra.css

extra:
  social: 
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Carto_ALex
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/alexander-fries-097685174/
    - icon: fontawesome/brands/github
      link: https://github.com/acfries

site_author: Alex Fries